name: random_uint8list
description: return a random Uint8List 
version: 1.0.1
homepage: https://github.com/rmw-dart/random_uint8list

environment:
  sdk: '>=2.14.3 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
